import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Departments from "@/components/Home/Departments";
import Services from "@/components/Home/Services";
import styles from "@/styles/Home.module.css";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Healthy Elite</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Departments />

        <Services />
        <Footer />

      </main>
    </>
  );
}
