import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header";
import BookDoctor from "@/components/Home/BookDoctor";
import Departments from "@/components/Home/Departments";
import Doctors from "@/components/Home/Doctors";
import EmergencyBooking from "@/components/Home/EmergencyBooking";
import Hero from "@/components/Home/Hero";
import OurProduct from "@/components/Home/OurProduct";
import SelectDoctor from "@/components/Home/SelectDoctor";
import Services from "@/components/Home/Services";
import WhyUS from "@/components/Home/WhyUS";
import Testimonial from "@/components/Testimonial/Testimonial";
import Head from "next/head";
import FindDoctor from "@/components/Home/FindDoctor";
import About from "@/components/Home/About";

export default function Home({ products, doctors }) {
  return (
    <>
      <Head>
        <title>Healthy Elite</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Hero></Hero>
        <EmergencyBooking></EmergencyBooking>
        <WhyUS />
        <Doctors />
        <FindDoctor/>
        <About/>
        <OurProduct products={products} />
        <Departments />

        <Services />
        <SelectDoctor />
        <BookDoctor doctors={doctors} />
        <Testimonial />
        <Footer />
      </main>
    </>
  );
}

export async function getStaticProps() {  
  const productResponse = await fetch(`http://localhost:3000/api/products`)
  const {products} = await productResponse.json() 
  const { doctors } = await import('/data/doctor.json');

  return {
    props: {
      products: products,
      doctors: doctors
    }
  }
}

